### ISSUE TITLE
Var global

### ISSUE THREAD

**Issue by victoriapenasmiro** [victoriapenasmiro/exercicis_dwec_202021#1]
https://github.com/victoriapenasmiro/exercicis_dwec_202021/blob/c074a16ff36964ffb5f4f75552f21e7843a6c3d5/Seccio-1%20nombres%20i%20strings/seccio1.js#L1

Hola @classicoman2
No entenc perquè si declar sa variable global "var valor" fóra de les funcions, si la vull emplear a les funcions no funciona, he de declararla a dins les funcions, aquesta variable la utiliztzaré a totes elles, per això volia treurer-la del codi.

Gracis

**Comment by classicoman2** [comment]
La raó de que no funcioni és doble,

1) perquè la instrucció s'executa just en carregar el fitxer .js i en iniciar-se la pàgina i en aquell moment, abans d'escriure cap text a dins, no té cap informació a dins
2) el més important! perquè la pàgina HTML encara no s'ha carregat quan s'executa aquella instrucció. És el **problema de càrrega de JS** que explico aquí:
https://docs.google.com/document/d/1cI9fjRlfIkbta83cdHI6X5RtATaIwrFrztUXIDaFqBc/edit#heading=h.v64nax8tg00k
