### ISSUE TITLE
No tenc clar l'enunciat

### ISSUE THREAD

**Issue by victoriapenasmiro** [victoriapenasmiro/exercicis_dwec_202021#2]
https://github.com/victoriapenasmiro/exercicis_dwec_202021/blob/0159973541268415149cd8bffa4308c3634a550b/Seccio-1%20nombres%20i%20strings/seccio1.js#L88

Hola @classicoman2,
No tenc molt clar l'objectiu de l'enunciat. ¿Es vol saber si no s'ha escrit cap caracter dins s'input o si s'han escrit espais en blanc?

Gracis

**Comment by classicoman2** [comment]
Bona pregunta. 

Podries donar per bona la segona interpretació, eliminar els espais en blanc emprant [aquesta funció de strings ](https://docs.google.com/document/d/1cI9fjRlfIkbta83cdHI6X5RtATaIwrFrztUXIDaFqBc/edit#heading=h.hlcd1l2voj63) i llavors la solució seria bona pels dos casos.
